<script>
    $(function() {
        $( "#datepickerdeb" ).datepicker({dateFormat :'dd-mm-yy', minDate: 0});
        $("#datepickerdeb").change(function(){
            var d = $("#datepickerdeb").datepicker('getDate');
            var n = new Date(d.getFullYear(), d.getMonth(), d.getDate() + 1);
            $("#datepickerfin").datepicker({dateFormat :'dd-mm-yy', minDate: n});
        });
    });
</script>
<div id="popup_tache_" class="ajout pop-up-block">
	<?php echo $this->form; ?>
</div>
