 <?php echo $this->doctype("HTML5"); ?>
<html>
	<head>
		<title>Suivi de projet</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<?php
			$this->headLink()	->appendStylesheet('/css/resetcss.css')
								->appendStylesheet('/css/style.css');
			echo $this->headLink();
								?>
		<link rel="stylesheet" href="http://code.jquery.com/ui/1.9.1/themes/base/jquery-ui.css" />
	    <script src="http://code.jquery.com/jquery-1.8.2.js"></script>
	    <script src="http://code.jquery.com/ui/1.9.1/jquery-ui.js"></script>
		<script src="/js/rouleau.js"></script>
	</head>
	<body>
		<div id="fade"></div>
		<div id="container">
			<header>
				<div id="entete"><h1>Suivi de projet</h1></div>
				<div id="connexion"><?php echo $this->layout()->login;?></div>		
			</header>
			<div id="page">
				<?php echo $this->layout()->content; ?>
			</div>
			<footer>
			</footer>
		</div>
	</body>
</html>
